- id: doi:10.1016/j.cell.2022.05.013
  authors:
    - Joseph M. Replogle
    - Reuben A. Saunders
    - Angela N. Pogson
    - Jeffrey A. Hussmann
    - Alexander Lenail
    - Alina Guna
    - Lauren Mascibroda
    - Eric J. Wagner
    - Karen Adelman
    - Gila Lithwick-Yanai
    - Nika Iremadze
    - Florian Oberstrass
    - Doron Lipson
    - Jessica L. Bonnar
    - Marco Jost
    - "**Thomas M. Norman&#42;**"
    - "Jonathan S. Weissman&#42;"
  buttons:
    - type: source
      link: https://gwps.wi.mit.edu/
- id: doi:10.1126/science.aax4438
  authors:
    - "**Thomas M. Norman&#42;**"
    - "Max A. Horlbeck&#42;"
    - Joseph M. Replogle
    - Alex Y. Ge
    - Albert Xu
    - Marco Jost
    - Luke A. Gilbert
    - Jonathan S. Weissman
  buttons:
    - type: source
      link: https://github.com/thomasmaxwellnorman/Perturbseq_GI
- id: doi:10.1016/j.cell.2016.11.048
  authors:
    - "Britt Adamson&#42;"
    - "**Thomas M. Norman&#42;**"
    - Marco Jost
    - Min Y. Cho
    - "James K. Nu\xF1ez"
    - Yuwen Chen
    - Jacqueline E. Villalta
    - Luke A. Gilbert
    - Max A. Horlbeck
    - Marco Y. Hein
    - Ryan A. Pak
    - Andrew N. Gray
    - Carol A. Gross
    - Atray Dixit
    - Oren Parnas
    - Aviv Regev
    - Jonathan S. Weissman
  buttons:
    - type: source
      link: https://github.com/thomasmaxwellnorman/perturbseq_demo
- id: doi:10.1038/s41590-023-01527-9
- id: doi:10.1126/science.aaw4506
- id: doi:10.1038/s41587-019-0387-5
- id: doi:10.1038/s41587-020-0470-y
- id: doi:10.1038/s41586-019-1184-5
- id: doi:10.1016/j.cell.2016.11.038
- id: doi:10.1016/j.cels.2016.04.002
- id: doi:10.1103/PhysRevLett.116.058101
- id: doi:10.1038/nature12804
- id: doi:10.1038/s43586-021-00093-4
- id: doi:10.1038/emboj.2011.36
- id: doi:10.1101/gad.1915010
- id: doi:10.1073/pnas.1002499107
- id: doi:10.1101/2024.07.26.605307
  type: preprint
  image: images/multiome_perturbseq_overview.png
  publisher: bioRxiv
  buttons:
    - type: twitter
      link: thenormanlab/status/1817964077848940765
      text: Summary
- id: doi:10.1101/2024.07.31.606073
  type: preprint
  image: images/crispra_overview.png
  publisher: bioRxiv
